Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WebsiteQuanLyBanHang.Models;

namespace WebsiteQuanLyBanHang.Controllers
{
    [Authorize(Roles ="Quantri")]
    public class QuanLyDonHangController : Controller
    {
        // GET: QuanLyDonHang
        WebQuanLyBanHangEntities db = new WebQuanLyBanHangEntities();
        public ActionResult ChuaThanhToan()
        {
            var lst = db.DonDatHangs.Where(n => n.DaThanhToan == false).OrderBy(n => n.NgayDat);
            return View(lst);
        }
        public ActionResult ChuaGiao()
        {
            var lstDSDHCG = db.DonDatHangs.Where(n => (n.TinhTrangGiao == false) && (n.DaThanhToan == true)).OrderBy(n => n.NgayDat);
            return View(lstDSDHCG);
        }
        public ActionResult DaGiaoDaThanhToan()
        {
            var lstDSDH = db.DonDatHangs.Where(n => n.TinhTrangGiao == true && n.DaThanhToan == true).OrderBy(n => n.NgayDat);
            return View(lstDSDH);
        }
        [HttpGet]
        public ActionResult DuyetDonHang(int? id)
        {
            if(id == null)
            {
                return HttpNotFound();
            }
            DonDatHang model = db.DonDatHangs.SingleOrDefault(n => n.MaDDH == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            var lstChiTietDH = db.ChiTietDonDatHangs.Where(n => n.MaDDH == id);
            ViewBag.lstChiTietDonHang = lstChiTietDH;
            return View(model);
        }
        [HttpPost]
        public ActionResult DuyetDonHang(DonDatHang DDH)
        {
            DonDatHang ddhUpDate = db.DonDatHangs.Single(n => n.MaDDH == DDH.MaDDH);
            ddhUpDate.DaThanhToan = DDH.DaThanhToan;
            ddhUpDate.TinhTrangGiao = DDH.TinhTrangGiao;

            string noidung;
            if (ddhUpDate.DaThanhToan == true)
            {
                if(ddhUpDate.TinhTrangGiao == true)
                {
                    //noidung = "Đơn hàng của bạn đã được giao thành công. Cảm ơn đã tin tưởng chúng tôi";
                    //GuiMail("THÔNG BÁO HOÀN TẤT ĐƠN HÀNG", ddhUpDate.KhachHang.Email, "lexuanluongllhh@gmail.com", "xuanluong21022002", noidung);
                    ddhUpDate.NgayGiao = DateTime.Now;
                    db.SaveChanges();
                    return RedirectToAction("DaGiaoDaThanhToan");

                }
                else
                {
                    //noidung = "Đơn hàng của bạn đã được đặt thành công";
                    //GuiMail("XÁC NHẬN ĐƠN HÀNG",ddhUpDate.KhachHang.Email,"lexuanluongllhh@gmail.com","xuanluong21022002",noidung);
                    return RedirectToAction("ChuaGiao");
                }
            }
            db.SaveChanges();
            return RedirectToAction("ChuaThanhToan");
        }
        public void GuiMail(string Title, string toMail,string fromMail,string Password, string Content) 
        {
            MailMessage mail = new MailMessage();
            mail.To.Add(toMail);
            mail.From = new MailAddress(fromMail);
            mail.Subject = Title;
            mail.Body = Content;
            mail.IsBodyHtml = true;
            mail.Priority = MailPriority.High;
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new System.Net.NetworkCredential(fromMail, Password);
            smtp.EnableSsl = true;
            smtp.Send(mail);
        }
    }   

}

Views/QuanLyDonHang/ChuaGiao.cshtml
@model IEnumerable<WebsiteQuanLyBanHang.Models.DonDatHang>
@{
    ViewBag.Title = "ChuaGiao";
    Layout = "~/Views/Shared/_AdminnLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng (Danh sách đơn hàng chưa thanh toán)</h2>
<br />
<ul class="navv nav-tabs">
    <li role="presentation" ><a href="@Url.Action("ChuaThanhToan","QuanLyDonHang")">Chưa thanh toán</a></li>
    <li role="presentation"class="active"><a href="@Url.Action("ChuaGiao","QuanLyDonHang")">Chưa giao và đã thanh toán</a></li>
    <li role="presentation"><a href="@Url.Action("DaGiaoDaThanhToan","QuanLyDonHang")">Đã giao và đã thanh toán</a></li>

</ul>
<br />
@grid.GetHtml(
    tableStyle: "gridTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",

    columns: grid.Columns(
        grid.Column("MaDDH", header: "Mã đơn đặt hàng"),
        grid.Column("MaKH", header: "Họ tên KH", format: p => p.MaKH != null ? p.KhachHang.TenKH : ""),
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiao", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi"),
        
        grid.Column(format: p => Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDDH }))
        )
    )

<style>
    h2 {
        text-align: center;
    }
    .navv {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
    }

        .navv > li {
            float: left;
            width: 33%;
        }

            .navv > li a {
                display: block;
                background: #d6b7eb;
                padding: 8px;
                border: 1px solid #d6b7eb;
                color: black;
                text-align: center;
            }

                .navv > li a:hover:not(.active) {
                    color: white;
                    background-color: rgb(228, 140, 196);
                    font-weight: bold;
                }

    .active {
        background-color: #58257b;
        color: white;
        font-weight: bold;
    }

    .gridTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .gridTable td {
            border: 1px solid #999999;
        }
</style>

Views/QuanLyDonHang/ChuaThanhToan.cshtml
@model IEnumerable<WebsiteQuanLyBanHang.Models.DonDatHang>
@{
    ViewBag.Title = "ChuaThanhToan";
    Layout = "~/Views/Shared/_AdminnLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng </h2>
<br />
<ul class="navv nav-tabs">
    <li role="presentation" class="active "><a href="@Url.Action("ChuaThanhToan","QuanLyDonHang")">Chưa thanh toán</a></li>
    <li role="presentation" ><a href="@Url.Action("ChuaGiao","QuanLyDonHang")">Chưa giao và đã thanh toán</a></li>
    <li role="presentation" ><a href="@Url.Action("DaGiaoDaThanhToan","QuanLyDonHang")">Đã giao và đã thanh toán</a></li>

</ul><br />
@grid.GetHtml(
    tableStyle: "gridTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",

    columns: grid.Columns(
        grid.Column("MaDDH", header:"Mã đơn đặt hàng"),
        grid.Column("MaKH", header:"Họ tên KH",format:p=>p.MaKH!=null?p.KhachHang.TenKH:""),
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiao", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi"),

        grid.Column(format:p=>Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new {id = p.MaDDH}))
        )
    )

<style>
    h2 {
        text-align: center;
    }
    .navv {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
    }

        .navv > li {
            float: left;
            width:33%;
        }

            .navv > li a {
                display: block;
                background: #d6b7eb;
                padding: 8px;
                border: 1px solid #d6b7eb;
                color: black;
                text-align:center;
            }

                .navv > li a:hover:not(.active) {
                    color: white;
                    background-color: rgb(228, 140, 196);
                    font-weight: bold;
                }
    .active {
        background-color: rgb(228, 140, 196);
        color: white;
        font-weight: bold;
    }
    .gridTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .gridTable td {
            border: 1px solid #999999;
        }
</style>

Views/QuanLyDonHang/DaGiaoDaThanhToan.cshtml
@model IEnumerable<WebsiteQuanLyBanHang.Models.DonDatHang>
@{
    ViewBag.Title = "ChuaGiao";
    Layout = "~/Views/Shared/_AdminnLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng </h2>
<br />
<ul class="navv nav-tabs">
    <li role="presentation"><a href="@Url.Action("ChuaThanhToan","QuanLyDonHang")">Chưa thanh toán</a></li>
    <li role="presentation" ><a href="@Url.Action("ChuaGiao","QuanLyDonHang")">Chưa giao và đã thanh toán</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("DaGiaoDaThanhToan","QuanLyDonHang")">Đã giao và đã thanh toán</a></li>

</ul>
<br />
@grid.GetHtml(
    tableStyle: "gridTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",

    columns: grid.Columns(
        grid.Column("MaDDH", header: "Mã đơn đặt hàng"),
        grid.Column("MaKH", header: "Họ tên KH", format: p => p.MaKH != null ? p.KhachHang.TenKH : ""),
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiao", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi")
        )
    )
<style>
    h2 {
        text-align: center;
    }
    .navv {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
    }

        .navv > li {
            float: left;
            width: 33%;
        }

            .navv > li a {
                display: block;
                background: #d6b7eb;
                padding: 8px;
                border: 1px solid #d6b7eb;
                color: black;
                text-align: center;
            }

                .navv > li a:hover:not(.active) {
                    color: white;
                    background-color: rgb(228, 140, 196);
                    font-weight: bold;
                }

    .active {
        background-color: #58257b;
        color: white;
        font-weight: bold;
    }

    .gridTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .gridTable td {
            border: 1px solid #999999;
        }
</style>

Views/QuanLyDonHang/DuyetDonHang.cshtml
@using WebsiteQuanLyBanHang.Models;
@model DonDatHang
@{
    ViewBag.Title = "DuyetDonHang";
    Layout = "~/Views/Shared/_AdminnLayout.cshtml";
}

<h2 style="text-align:center">Thông tin đơn hàng</h2>
<br />
<br />

@using (Html.BeginForm("DuyetDonHang", "QuanLyDonHang"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Hidden("MaDDH", Model.MaDDH);
    <div class="ChiTietDonHang table">
        @{ IEnumerable<ChiTietDonDatHang> lstChiTietDonHang = (IEnumerable<ChiTietDonDatHang>)ViewBag.lstChiTietDonHang;}
        <table class="table" id="table">
            <tr>
                <td colspan="4">
                    <table style="width:100%">
                        <tr>
                            <td>Mã đơn hàng: @Model.MaDDH </td>
                            <td>Mã khách hàng: @Model.KhachHang.MaKH</td>
                            <td>Tên khách hàng: @Model.KhachHang.TenKH</td>
                            <td>Địa chỉ:@Model.KhachHang.DiaChi</td>
                            <td>Ngày đặt: @Model.NgayDat.Value.ToString("dd/MM/yyyy")</td>
                            @if (Model.DaThanhToan == false)
                            {
                                <td>Thanh toán: @Html.EditorFor(model => model.DaThanhToan) </td>
                            }
                            else
                            {
                                <td style="display:none">Thanh toán: @Html.EditorFor(model => model.DaThanhToan) </td>
                            }

                            <td>Đã giao: @Html.EditorFor(model => model.TinhTrangGiao) </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td><b>Sản phẩm</b></td>

                <td><b>Số lượng đặt</b></td>
                <td><b>Đơn giá đặt</b></td>
            </tr>
            
            @foreach (var item in lstChiTietDonHang)
            {
                <tr>
                    <td>@item.SanPham.TenSP</td>

                    <td>@item.SoLuong</td>
                    <td>@item.DonGia</td>
                </tr>
            }
            <tr>
                <td align="right" colspan="4">Tổng số lượng: @Model.ChiTietDonDatHangs.Sum(n => n.SoLuong) sản phẩm</td>
            </tr>
            <tr>
                <td align="right" colspan="4">Tổng tiền : @Model.ChiTietDonDatHangs.Sum(n => n.SanPham.DonGia).Value.ToString("#,##") đồng</td>
            </tr>
        </table>
        <br /><br />
        <input type="button" value="In đơn hàng" id="btnInDonHang" />
        <input type="submit" value="Lưu đơn hàng"class="btn-danger" id="btnLuuDonHang" />
    </div>
}
<script>
    var input = document.getElementById('btnInDonHang');
    input.onclick = function () {
        var content = "<table>" + $("#table").html() + "<table>";
        InDonHang(content);
    };
    function InDonHang(content) {
        var printWindow = window.open('', '', 'height=400,width=800');
        printWindow.document.write('<html><head><title>DIV Contents</title>');
        printWindow.document.write('</head><body>');
        printWindow.document.write(content);
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();

    }
</script>