Models/ThanhVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhVien()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int MaTV { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string CauHoi { get; set; }
        public string CauTraLoi { get; set; }
        public Nullable<int> MaLoaiTV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
    }
}

Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteQuanLyBanHang.Models;

namespace WebsiteQuanLyBanHang.Controllers
{
    [Authorize(Roles = "Quantri")]
    public class ThongKeController : Controller
    {
        // GET: ThongKe
        WebQuanLyBanHangEntities db = new WebQuanLyBanHangEntities();
        public ActionResult Index()
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();
            ViewBag.TongDoanhThu = ThongKeTongDoanhThu();
            ViewBag.TongDonHang = ThongKeDonHang();
            ViewBag.TongThanhVien = ThongKeDThanhVien();
            return View();
        }
        [HttpPost]
        public ActionResult Index(int thang,int nam)
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();
            ViewBag.TongDoanhThu = ThongKeTongDoanhThu();
            ViewBag.TongDonHang = ThongKeDonHang();
            ViewBag.TongThanhVien = ThongKeDThanhVien();
            IEnumerable<DonDatHang> lstDDH;
            if (thang != 0)
            {
                lstDDH = db.DonDatHangs.Where(n => n.NgayDat.Value.Month == thang && n.NgayDat.Value.Year == nam);
                ViewBag.TongThongKe = ThongKeDoanhThuThang(thang,nam);
                ViewBag.lstDDH = db.DonDatHangs.Where(n => n.NgayDat.Value.Month == thang && n.NgayDat.Value.Year == nam);
                return View(db.DonDatHangs.Where(n => n.NgayDat.Value.Month == thang && n.NgayDat.Value.Year == nam));
            }
            else
            {
                ViewBag.TongThongKe = ThongKeDoanhThuNam( nam);
                lstDDH = db.DonDatHangs.Where(n => n.NgayDat.Value.Year == nam);
                ViewBag.lstDDH = db.DonDatHangs.Where(n => n.NgayDat.Value.Year == nam);
                return View(db.DonDatHangs.Where(n => n.NgayDat.Value.Year == nam));
            }
            
        }
        public decimal ThongKeTongDoanhThu()
        {
            decimal tongDoanhThu = db.ChiTietDonDatHangs.Sum(n => n.SoLuong * n.DonGia).Value;
            return tongDoanhThu/1000;
        } 
        public double ThongKeDonHang()
        {
            
            var slddh = db.DonDatHangs.Count();
            return slddh;
        } 
        public double ThongKeDThanhVien()
        {
            
            var slTV = db.ThanhViens.Count();
            return slTV;
        }
        public decimal ThongKeDoanhThuThang(int thang,int nam)
        {
            var lstDDH = db.DonDatHangs.Where(n=>n.NgayDat.Value.Month == thang && n.NgayDat.Value.Year == nam);
            decimal tongDoanhThu = 0;
            foreach (var item in lstDDH) 
            {
                tongDoanhThu +=decimal.Parse(item.ChiTietDonDatHangs.Sum(n => n.SoLuong * n.DonGia).Value.ToString());
            }
            return tongDoanhThu;
        }
        public decimal ThongKeDoanhThuNam(int nam)
        {
            var lstDDH = db.DonDatHangs.Where(n=> n.NgayDat.Value.Year == nam);
            decimal tongDoanhThu = 0;
            foreach (var item in lstDDH) 
            {
                tongDoanhThu +=decimal.Parse(item.ChiTietDonDatHangs.Sum(n => n.SoLuong * n.DonGia).Value.ToString());
            }
            return tongDoanhThu;
        }
        public ActionResult TongDoanhThu()
        {
            ViewBag.TongDoanhThu = ThongKeTongDoanhThu();

            return View(db.DonDatHangs);
        }
        public ActionResult ThanhVien()
        {
            var lstTV = db.ThanhViens.Where(n => n.MaLoaiTV == 5 || n.MaLoaiTV == 6);
            return View(lstTV);
        }
    }
}

Views/ThongKe/Index.cshtml
@using WebsiteQuanLyBanHang.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminnLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<div class="row">
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
            <div class="inner">
                <h3>@ViewBag.TongDonHang</h3>

                <p>Đơn hàng</p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="#" class="small-box-footer">Xem thêm chi tiết <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">

                <h3>@ViewBag.TongDoanhThu.ToString("#,##") K</h3>

                <p>Doanh thu</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="@Url.Action("TongDoanhThu", "ThongKe")" class="small-box-footer">Xem thêm chi tiết<i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-warning">
            <div class="inner">
                <h3>@ViewBag.TongThanhVien</h3>

                <p>Thành viên</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="@Url.Action("ThanhVien","ThongKe")" class="small-box-footer">Xem thêm chi tiết<i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-danger">
            <div class="inner">
                <h3>@ViewBag.SoNguoiTruyCap</h3>

                <p>Người truy cập</p>
            </div>
            <div class="icon">
                <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">Xem thêm chi tiết<i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<h3 style="text-align:center">Thống kê</h3>
<hr />
@using (Html.BeginForm())
{
    <div>
        <table>
            <tr>
                <td>
                    <div class="col-md-2">
                        Tháng:
                    </div>
                </td>
                <td>
                    <div class="col-md-2">
                        Năm:
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="col-md-12">

                        <select id="monthSelect" name="thang">
                            <option value="0">-- Chọn tháng--</option>
                            @for (int month = 12; month >= 1; month--)
                            {
                                <option value="@month">@month</option>
                            }
                        </select>
                    </div>

                </td>
                <td>
                    <div class="col-md-12">

                        <select id="yearSelect" name="nam">
                            <option value="">-- Chọn năm --</option>
                            @for (int year = DateTime.Now.Year; year >= 2020; year--)
                            {
                                <option value="@year">@year</option>
                            }
                        </select>
                    </div>
                </td>
                <td>
                    <div class="col-md-2">
                        <input type="submit" class="btn-danger" value="Xem kết quả">
                    </div>
                </td>
            </tr>

        </table>

        <hr />
    </div>
}
@if (Model == null || Model.Count() == 0)
{


    <br />
    <h3 style="text-align:center;">Không có đơn hàng trong thời gian này</h3>
}
else
{
    <table class="table">
        <tr style="font-weight: bold; background: rgb(226, 105, 232)">
            <td>Mã đơn</td>
            <td>Mã khách hàng</td>
            <td>Tên khách hàng</td>
            <td>Ngày đặt</td>
            <td>Ngày giao</td>
            <td>Tổng tiền đơn</td>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.MaDDH</td>
                <td>@item.MaKH</td>
                <td>@item.KhachHang.TenKH</td>
                <td>@item.NgayDat.Value.ToString("dd/MM/yyyy")</td>
                @if (item.NgayGiao != null)
                {
                    <td>@item.NgayGiao.Value.ToString("dd/MM/yyyy")</td>
                }
                else
                {
                    <td></td>
                }

                <td>@item.ChiTietDonDatHangs.Sum(n => n.SanPham.DonGia).Value.ToString("#,##")</td>
            </tr>
        }

        <tr style="font-weight: bold; background: rgb(226, 105, 232)">
            <td style="text-align:left;">Tổng doanh thu:</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td >@ViewBag.TongThongKe.ToString("#,##") VND</td>
        </tr>
    </table>
}

Views/ThongKe/ThanhVien.cshtml
@using WebsiteQuanLyBanHang.Models;
@model IEnumerable<ThanhVien>
@{
    ViewBag.Title = "ThanhVien";
    Layout = "~/Views/Shared/_AdminnLayout.cshtml";
}

<h2 style="position: absolute; left: 47%;">Danh sách thành viên</h2>
<br /><hr />
<table class="table">
    <tr style="background:rgb(226, 105, 232)">
        <td>Mã thành viên</td>
        <td>Tên thành viên</td>
        <td>Tên tài khoản</td>
        <td>Địa chỉ</td>
        <td>Email</td>
        <td>SDT</td>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.MaTV</td>
            <td>@item.HoTen</td>
            <td>@item.TaiKhoan</td>
            <td>@item.DiaChi</td>
            <td>@item.Email</td>
            <td>@item.SDT</td>
            
        </tr>
    }
</table>

Views/ThongKe/TongDoanhThu.cshtml
@using WebsiteQuanLyBanHang.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "TongDoanhThu";
    Layout = "~/Views/Shared/_AdminnLayout.cshtml";
}
<h2 style="position:absolute;left:47%;">Tổng doanh thu</h2>
<br /><hr />
@if (Model == null || Model.Count() == 0)
{
}
else
{
    <table class="table">
        <tr style="background:rgb(226, 105, 232)">
            <td>Mã đơn</td>
            <td>Mã khách hàng</td>
            <td>Tên khách hàng</td>
            <td>Ngày đặt</td>
            <td>Ngày giao</td>
            <td>Tổng tiền đơn</td>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.MaDDH</td>
                <td>@item.MaKH</td>
                <td>@item.KhachHang.TenKH</td>
                <td>@item.NgayDat.Value.ToString("dd/MM/yyyy")</td>
                @if (item.NgayGiao != null)
                {
                    <td>@item.NgayGiao.Value.ToString("dd/MM/yyyy")</td>
                }
                else
                {
                    <td></td>
                }

                <td>@item.ChiTietDonDatHangs.Sum(n => n.SanPham.DonGia).Value.ToString("#,##")</td>
            </tr>
        }

        <tr style="font-weight: bold; background: rgb(226, 105, 232)">
            <td style="text-align:left;">Tổng doanh thu:</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>@ViewBag.TongDoanhThu.ToString("#,##")K VND</td>
        </tr>
    </table>
}