Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhChons = new HashSet<BinhChon>();
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string CauHinh { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public string HinhAnh1 { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotBinhChon { get; set; }
        public Nullable<int> LuotBinhluan { get; set; }
        public Nullable<int> SoLanMua { get; set; }
        public Nullable<int> Moi { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<int> MaLoaiSp { get; set; }
        public Nullable<bool> DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhChon> BinhChons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}

Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteQuanLyBanHang.Models;

namespace WebQuanLyBanHang.Controllers
{
    public class SanPhamController : Controller
    {
        WebQuanLyBanHangEntities db = new WebQuanLyBanHangEntities ();
        // GET: SanPham
        [ChildActionOnly]
        public ActionResult SanPhamStyle1()
        {
            return PartialView();
        }
        [ChildActionOnly]
        public ActionResult SanPhamStyle2()
        {
            return PartialView();
        }
        public ActionResult XemChiTietSp(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id && n.DaXoa == false);
            if (sp == null)
            {
                return HttpNotFound();
            }
            return View(sp);
        }

        public ActionResult SanPham(int? MaLoaiSP, int? MaNSX) 
        {
            if (MaLoaiSP == null|| MaNSX==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var lstSP = db.SanPhams.Where(n=>n.MaLoaiSp==MaLoaiSP && n.MaNSX==MaNSX);
            if (lstSP.Count() == 0)
            {
                return HttpNotFound();
            }
            return View();
        }
    }
}

Views/SanPham/SanPhamStyle1.cshtml
@using WebsiteQuanLyBanHang.Models
@model IEnumerable<SanPham>


@foreach (var item in Model.Take(2))
{
    <div class="col-md-4 grid-top">
        <a href="@Url.Action("XemChiTietSp","SanPham", new { id = item.MaSP })" class="b-link-stripe b-animate-go  thickbox">
            <img class="img-responsive" src=@Url.Content("~/content/HinhAnhSP/"+item.HinhAnh) alt="">
        </a>

        <p><a href="~/Controllers/SanPham/XemChiTietSp">@item.TenSP</a></p>
    </div>
}
<div class="clearfix"> </div>

Views/SanPham/SanPhamStyle2.cshtml
@model IEnumerable<WebsiteQuanLyBanHang.Models.SanPham>

<div class="content-top-bottom">
    <h2>Máy tính mới nhất</h2>
    <div class="col-md-6 men">
        <a href="single.html" class="b-link-stripe b-animate-go  thickbox">
            <img class="img-responsive" src=@Url.Content("~/content/HinhAnhSP/"+Model.ElementAt(0).HinhAnh) alt="">
            <div class="b-wrapper">

                <h3 class="b-animate b-from-top top-in   b-delay03 ">
                    <span>@Html.Raw(Model.ElementAt(0).TenSP)</span>
                </h3>
            </div>
        </a>

    </div>
    <div class="col-md-6">
        <div class="col-md1 ">
            <a href="single.html" class="b-link-stripe b-animate-go  thickbox">
                <img class="img-responsive" src=@Url.Content("~/content/HinhAnhSP/"+Model.ElementAt(1).HinhAnh) alt="">
                <div class="b-wrapper">
                    <h3 class="b-animate b-from-top top-in1   b-delay03 ">
                        <span>@Html.Raw(Model.ElementAt(1).TenSP)</span>
                    </h3>
                </div>
            </a>

        </div>
        <div class="col-md2">
            <div class="col-md-6 men1">
                <a href="single.html" class="b-link-stripe b-animate-go  thickbox">
                    <img class="img-responsive" src=@Url.Content("~/content/HinhAnhSP/"+Model.ElementAt(2).HinhAnh) alt="">
                    <div class="b-wrapper">
                        <h3 class="b-animate b-from-top top-in2   b-delay03 ">
                            <span>@Html.Raw(Model.ElementAt(2).TenSP)</span>
                        </h3>
                    </div>
                </a>

            </div>
            <div class="col-md-6 men2">
                <a href="single.html" class="b-link-stripe b-animate-go  thickbox">
                    <img class="img-responsive" src=@Url.Content("~/content/HinhAnhSP/"+Model.ElementAt(3).HinhAnh) alt="">
                    <div class="b-wrapper">
                        <h3 class="b-animate b-from-top top-in2   b-delay03 ">
                            <span>@Html.Raw(Model.ElementAt(3).TenSP)</span>
                        </h3>
                    </div>
                </a>

            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <div class="clearfix"> </div>
</div>

Views/SanPham/XemChiTietSp.cshtml
@model WebsiteQuanLyBanHang.Models.SanPham
@{
    ViewBag.Title = "XemChiTietSp";
    Layout = "~/Views/Shared/_ProductLayout.cshtml";
}

<div class="col-md-9 product-price1">
    <div class="col-md-5 single-top">
        <div class="flexslider">
            <ul class="slides">
                <li data-thumb="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh)">
                    <img src="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh)" />
                </li>
                <li data-thumb="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh1)">
                    <img src="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh1)" />
                </li>
                <li data-thumb="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh2)">
                    <img src="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh2)" />
                </li>
                <li data-thumb="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh3)">
                    <img src="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh3)" />
                </li>
            </ul>
        </div>
        <!-- FlexSlider -->
        <script defer src="~/Content/js/jquery.flexslider.js"></script>
        <link href="~/Content/css/flexslider.css" rel="stylesheet" type="text/css" media="screen" />
        <script>
            // Can also be used with $(document).ready()
            $(window).load(function () {
                $('.flexslider').flexslider({
                    animation: "slide",
                    controlNav: "thumbnails"
                });
            });
        </script>
    </div>
    <div class="col-md-7 single-top-in simpleCart_shelfItem">
        <div class="single-para ">
            <h4>@Model.TenSP</h4>
            <div class="star-on">
                <ul class="star-footer">
                    <li><a href="#"><i> </i></a></li>
                    <li><a href="#"><i> </i></a></li>
                    <li><a href="#"><i> </i></a></li>
                    <li><a href="#"><i> </i></a></li>
                    <li><a href="#"><i> </i></a></li>
                </ul>
                <div class="review">
                    <a href="#"> 1 customer review </a>

                </div>
                <div class="clearfix"> </div>
            </div>

            <h5 class="item_price">@Model.DonGia.Value.ToString("#,##")VND</h5>
            <p>
                @Html.Raw(Model.CauHinh)
            </p>
            <a href="@Url.Action("ThemGioHang","GioHang", new {@MaSP=Model.MaSP,@URl=Request.Url.ToString()})" class="btn add-cart" id="add-GH" >Thêm vào giỏ hàng</a>
         

        </div>
    </div>
    <div class="clearfix"> </div>
    <h4>Thông tin sản phẩm </h4>
    @Html.Raw(Model.MoTa)
    <hr />
    <!---->
   
</div>